### ISSUE TITLE
Request for a new script

### ISSUE THREAD

**Issue by hyukishi** [aaronmweiss/DOCTL-Remote-Snapshot#1]
This is not an Issue report, but rather a request for an enhancement in the form of a separate script.

What I would like to see is a script that only handles the deletion/retention of snapshots for all droplet IDs without the need to supply the droplet IDs individually. I'm sure this is possible by hacking away at the original script.

I would also like the retention value to be stored within the script directly. In my case it would be keeping the 2 latest snapshots per droplet ID.

Thank you for your consideration.

**Comment by aaronmweiss** [comment]
Thank you for the suggestion. I've been considering ways to implement additional droplets.

To obtain clarification, are you looking for a completely separate script that does not create a snapshot, but simply deletes all snapshots from all droplets within an account up to a certain retention value? Please confirm.

**Comment by hyukishi** [comment]
That's exactly what I was looking for. I've managed to hack something together but I'm sure your solution would be much more elegant just by looking at your original script.



What I ended up with used some sorting and sed magic along with a temporary file to compile the snapshot IDs and feed them to the doctl compute snapshot delete <id> -f argument until the list has been exhausted. Looks like a mess to me, but it works. Let me know if you'd like to see it and I'll post it as a gist on my GitHub gists page.

**Comment by aaronmweiss** [comment]
Yeah, that would be a separate script, but based on my understanding of DOCTL, it sounds like it can be done. 

Given that, this would certainly be out of scope for this repo. Also, I personally don't have a use-case for this nor the time to dedicate to it to develop something like that. You're welcome to email me at g i t h u b @ a a r o n w e i s s . m e (without those spaces for spam deterrent) and we can discuss something for the distant future.
